# Generated by Django 3.1 on 2020-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtikelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(upload_to=None)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('Tutorial', 'Tutorial'), ('Opini', 'Opini'), ('Filsafat', 'Filsafat'), ('Politik', 'Politik'), ('Ekonomi', 'Ekonomi'), ('Pemrograman', 'Pemrograman'), ('Cyber Security', 'Cyber Security')], max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publish', models.DateTimeField()),
                ('update', models.DateTimeField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
